In [2]:
import numpy as np

In [3]:
lst = [1, 2, 3, 4, 5]
type(lst)

list

In [4]:
arr = np.array(lst)
type(arr)
arr2 = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr2.ndim,arr2.shape,arr2.size,arr2.dtype,arr2.itemsize,arr2.nbytes,sep='\n')

2
(3, 5)
15
int32
4
60


In [5]:
arr3 = arr2.reshape(5,3) # or np.reshape(arr2,(5,3))
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [6]:
arr4,arr5 = np.zeros((3,5)),np.ones((3,5))
print(arr4,arr5,sep="\n")

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
arr5 = np.random.random((3,3))
print(arr5,arr5.flatten(),sep="\n-----\n")

[[0.09074171 0.1677236  0.48987322]
 [0.02883917 0.41738694 0.8746012 ]
 [0.01314242 0.9041856  0.6965134 ]]
-----
[0.09074171 0.1677236  0.48987322 0.02883917 0.41738694 0.8746012
 0.01314242 0.9041856  0.6965134 ]


In [8]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [10]:
arr6 = np.arange(1,10,1)
arr6+=1
print(arr6,arr6+1,arr6-1,arr6*2,arr6/2,arr6**2,arr6%5,arr6.min(),arr6.max(),sep="\n")

[ 2  3  4  5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10 11]
[1 2 3 4 5 6 7 8 9]
[ 4  6  8 10 12 14 16 18 20]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[  4   9  16  25  36  49  64  81 100]
[2 3 4 0 1 2 3 4 0]
2
10


In [11]:
arr7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr7.max(axis=0),arr7.max(axis=1),arr7.min(axis=0),arr7.min(axis=1),arr7.sum(),sep="\n")
# axis=0 means column wise and axis=1 means row wise

[7 8 9]
[3 6 9]
[1 2 3]
[1 4 7]
45


In [12]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.arange(9,0,-1).reshape(3,3)
print(arr1*arr2,arr1.dot(arr2),arr1+arr2,sep="\n")

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [13]:
arr3 = np.arange(1,9,1).reshape(2,4)
arr4 = np.arange(8,0,-1).reshape(4,2)
print(arr3.dot(arr4),arr4.dot(arr3),sep="\n")

[[ 40  30]
 [120  94]]
[[43 58 73 88]
 [31 42 53 64]
 [19 26 33 40]
 [ 7 10 13 16]]


In [14]:
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr5[:,:],arr5[:1,:3],arr5[:,:1],arr5[:][:1],sep="\n\n")
# arr5[:1,:3] means 1st row and 3 columns
# arr5[:,:1] means all rows and 1st column
# arr5[:][:1] means all rows and 1st row

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]]

[[1]
 [4]
 [7]]

[[1 2 3]]


In [20]:
arr = np.array([[7,3,8,6,4],[7,2,9,8,6],[5,4,3,2,1]])
print(np.sort(arr,axis=1,kind='mergesort'),np.sort(arr,axis=0,kind='mergesort'),np.sort(arr,kind='mergesort'),sep="\n\n")

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]

[[5 2 3 2 1]
 [7 3 8 6 4]
 [7 4 9 8 6]]

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]


In [24]:
arr1 = np.arange(1,9,1).reshape(2,4)
arr2 = np.arange(8,0,-1).reshape(2,4)
print(arr3:=np.vstack((arr1,arr2)),np.hstack((arr1,arr2)),np.concatenate((arr1,arr2),axis=0),np.concatenate((arr1,arr2),axis=1),sep="\n\n")

[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]

[[1 2 3 4 8 7 6 5]
 [5 6 7 8 4 3 2 1]]

[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]

[[1 2 3 4 8 7 6 5]
 [5 6 7 8 4 3 2 1]]


In [30]:
print(arr3,np.hsplit(arr3,2),np.vsplit(arr3,2),sep="\n\n")

[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]

[array([[1, 2],
       [5, 6],
       [8, 7],
       [4, 3]]), array([[3, 4],
       [7, 8],
       [6, 5],
       [2, 1]])]

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[8, 7, 6, 5],
       [4, 3, 2, 1]])]


In [38]:
lst = [x for x in range(1,11)]
len([j for j in lst if j>5])

5

In [42]:
lst  = np.arange(1,11,1)
print(len(lst[lst > 5]),lst[lst > 5],sep="\n")

5
[ 6  7  8  9 10]


In [43]:
print(len(lst[lst%3==0]),lst[lst%3==0],sep="\n")

3
[3 6 9]


In [1]:
import numpy as np

# An array with 2 rows and integer data type
myarray = np.eye(2, dtype=int)

print(myarray)

[[1 0]
 [0 1]]
