In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_boston

data = load_boston()
x = data.data
y = data.target
features = data.feature_names
print(x,y,features,sep='\n\n')

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19

C:\Users\ANURAG\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Californi

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(404, 13) (102, 13) (404,) (102,)


In [3]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100)
rf.fit(x_train, y_train)
rf_pred = rf.predict(x_test)
rf_pred

array([17.045, 20.964, 20.769, 20.308, 11.845, 27.134, 19.901, 15.637,
       22.123, 26.081, 19.859, 20.905, 30.608, 45.734, 21.089, 40.43 ,
       34.687, 19.519, 44.009, 30.915, 11.725, 32.298, 19.96 , 33.928,
       20.805, 33.415, 30.467, 11.763, 24.188, 13.132, 19.58 , 22.9  ,
       21.516, 22.337, 34.964, 21.279, 21.911, 12.754, 21.626, 14.576,
       21.011, 11.354, 43.569, 33.077, 20.618, 18.869, 46.541, 21.756,
       23.034, 19.631, 19.868, 13.196, 34.092, 15.849, 23.243, 24.926,
       37.349, 20.694, 15.684, 14.864, 15.623,  7.188, 28.467, 16.606,
       32.406, 20.404, 20.147, 32.62 , 26.203, 36.107, 21.669, 15.606,
       16.091, 24.77 , 12.922, 15.411, 21.125, 27.437,  8.514, 19.002,
       10.734, 21.366,  9.287, 14.683, 32.163, 27.98 , 33.906, 23.811,
       24.781, 19.579, 20.823, 15.335, 15.712, 23.632, 25.669, 26.506,
       20.436, 22.978, 16.311, 18.269, 34.774, 13.798])

In [4]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, rf_pred)

9.220295372549012

K-Fold Cross Validation

In [7]:
from sklearn.model_selection import KFold

kfold = KFold(n_splits=5, shuffle=False)

for train_index, test_index in kfold.split(x):
    print("TRAIN:", train_index, "\nTEST:", test_index)
    print("\n-------------\n")

TRAIN: [102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155
 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173
 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191
 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209
 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227
 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245
 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263
 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281
 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299
 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317
 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335
 336 337 338 339 340 341 342 343 344 345 346

In [11]:
n_est = [100, 200, 500]

for n_estimator in n_est:       
    error = []
    for train_index, test_index in kfold.split(x):
        
        x_train, x_test = x[train_index], x[test_index]
        y_train, y_test = y[train_index], y[test_index]
    
        rf1 = RandomForestRegressor(n_estimator)

        rf1 = rf1.fit(x_train, y_train)

        prediction = rf1.predict(x_test)
        
        error.append(mean_squared_error(y_test, prediction))
    print("Results for n_estimator: ", n_estimator)
    print(error)
    print("Average Error = ", sum(error)/len(error))

Results for n_estimator:  100
[8.41830998039215, 12.663970900990131, 20.262532207920763, 46.994589851485124, 19.933382653465326]
Average Error =  21.6545571188507
Results for n_estimator:  200
[7.890407313725497, 13.193318900990132, 21.426639653465333, 46.27063167079206, 19.909139044554475]
Average Error =  21.7380273167055
Results for n_estimator:  500
[7.833581905882376, 13.375735970296875, 21.681659529108995, 46.08101053148526, 18.034923979405985]
Average Error =  21.401382383235898
